=== oirlab/tmt-crds/crds/tmt/subarrays/SubarraysXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SubarrayValues">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="Instrument"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Instrument">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="InstrumentName" type="InstrumentName"/>
				<xs:element maxOccurs="unbounded" ref="Subarray"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Subarray">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SubarrayName" type="SubarrayName"/>
				<xs:element name="Rows" type="xs:unsignedInt"/>
				<xs:element name="Columns" type="xs:unsignedInt"/>
				<xs:element maxOccurs="unbounded" ref="FrameTime"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="DisperserCorners"/>
				<xs:element name="USEAFTERDATE" type="UTCDateType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FrameTime">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="ReadoutPattern" type="ReadoutPatternType"/>
				<xs:element minOccurs="0" name="NumOutputs" type="NumOutputsType"/>
				<xs:element name="FrameReadTime" type="FrameReadTimeType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DisperserCorners">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NRSDisperser" type="xs:string"/>
				<xs:element name="RowCorner" type="DisperserCornerType"/>
				<xs:element name="NRS1ColumnCorner" type="DisperserCornerType"/>
				<xs:element name="NRS2ColumnCorner" type="DisperserCornerType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="InstrumentName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FGS"/>
			<xs:enumeration value="MIRI"/>
			<xs:enumeration value="NIRCAM"/>
			<xs:enumeration value="NIRSPEC"/>
			<xs:enumeration value="NIRISS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SubarrayName">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NumOutputsType">
		<xs:restriction base="xs:unsignedInt">
			<xs:enumeration value="1"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ReadoutPatternType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FrameReadTimeType">
		<xs:restriction base="xs:double">
			<xs:minInclusive value=".000001"/>
			<xs:maxInclusive value="50.00000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DisperserCornerType">
		<xs:restriction base="xs:unsignedInt">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="2048"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UTCDateType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{4}-\d{3}/([01]\d|2[0-3]):[0-5]\d:[0-5]\d"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== oirlab/tmt-crds/crds/tmt/subarrays/SubarraysXML.xml
<?xml version='1.0' encoding='UTF-8'?>
<SubarrayValues xsi:noNamespaceSchemaLocation="SubarraysXML.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- MIRI Subarrays *************************************** -->
  <Instrument>
    <InstrumentName>MIRI</InstrumentName>
    <Subarray>
      <SubarrayName>FULL</SubarrayName>
      <Rows>1032</Rows>
      <Columns>1024</Columns>
      <FrameTime>
    <ReadoutPattern>SLOW</ReadoutPattern>
    <FrameReadTime>23.88992</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>2.77504</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>2.77504</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>BRIGHTSKY</SubarrayName>
      <Rows>512</Rows>
      <Columns>512</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.86528</FrameReadTime>
      </FrameTime>
      <FrameTime> 
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.86528</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB256</SubarrayName>
      <Rows>256</Rows>
      <Columns>256</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.29952</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.29952</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB128</SubarrayName>
      <Rows>128</Rows>
      <Columns>128</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.11904</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.11904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB64</SubarrayName>
      <Rows>72</Rows>
      <Columns>64</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.08512</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.08512</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUBPRISM</SubarrayName>
      <Rows>72</Rows>
      <Columns>416</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.15904</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.15904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SLITLESSPRISM</SubarrayName>
      <Rows>72</Rows>
      <Columns>416</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.15904</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.15904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK1065</SubarrayName>
      <Rows>288</Rows>
      <Columns>224</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK1140</SubarrayName>
      <Rows>288</Rows>
      <Columns>224</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK1550</SubarrayName>
      <Rows>288</Rows>
      <Columns>224</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>    
    <FrameReadTime>0.23968</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASKLYOT</SubarrayName>
      <Rows>320</Rows>
      <Columns>304</Columns>
      <FrameTime>
    <ReadoutPattern>FAST</ReadoutPattern>
    <FrameReadTime>0.32400</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <ReadoutPattern>FASTGRPAVG</ReadoutPattern>
    <FrameReadTime>0.32400</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
  </Instrument>

  <!-- NIRCAM Subarrays *************************************** -->
  <Instrument>
    <InstrumentName>NIRCAM</InstrumentName>
    <Subarray>
          <SubarrayName>FULL</SubarrayName>
      <Rows>2048</Rows>
      <Columns>2048</Columns>
      <FrameTime>
    <NumOutputs>4</NumOutputs>
    <FrameReadTime>10.73677</FrameReadTime>
      </FrameTime>
      <FrameTime>
    <NumOutputs>1</NumOutputs>
    <FrameReadTime>42.20940</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB160</SubarrayName>
      <Rows>160</Rows>
      <Columns>160</Columns>
      <FrameTime>
    <FrameReadTime>0.27864</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB320</SubarrayName>
      <Rows>320</Rows>
      <Columns>320</Columns>
      <FrameTime>
    <FrameReadTime>1.06904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB640</SubarrayName>
      <Rows>640</Rows>
      <Columns>640</Columns>
      <FrameTime>
    <FrameReadTime>4.18584</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK210R</SubarrayName>
      <Rows>640</Rows>
      <Columns>640</Columns>
      <FrameTime>
    <FrameReadTime>4.18584</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASKSWB</SubarrayName>
      <Rows>640</Rows>
      <Columns>640</Columns>
      <FrameTime>
    <FrameReadTime>4.18584</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK335R</SubarrayName>
      <Rows>320</Rows>
      <Columns>320</Columns>
      <FrameTime>
    <FrameReadTime>1.06904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASK430R</SubarrayName>
      <Rows>320</Rows>
      <Columns>320</Columns>
      <FrameTime>
    <FrameReadTime>1.06904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>MASKLWB</SubarrayName>
      <Rows>320</Rows>
      <Columns>320</Columns>
      <FrameTime>
    <FrameReadTime>1.06904</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB400P</SubarrayName>
      <Rows>400</Rows>
      <Columns>400</Columns>
      <FrameTime>
    <FrameReadTime>1.65624</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB160P</SubarrayName>
      <Rows>160</Rows>
      <Columns>160</Columns>
      <FrameTime> 
    <FrameReadTime>0.27864</FrameReadTime>
      </FrameTime> 
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB64P</SubarrayName>
      <Rows>64</Rows>
      <Columns>64</Columns>
      <FrameTime>
    <FrameReadTime>0.05016</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB96DHSPILA</SubarrayName>
      <Rows>96</Rows>
      <Columns>96</Columns>
      <FrameTime>
    <FrameReadTime>0.10584</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB96DHSPILB</SubarrayName>
      <Rows>96</Rows>
      <Columns>96</Columns>
      <FrameTime>
    <FrameReadTime>0.10584</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB64FP1A</SubarrayName>
      <Rows>64</Rows>
      <Columns>64</Columns>
      <FrameTime>
    <FrameReadTime>0.05016</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB64FP1B</SubarrayName>
      <Rows>64</Rows>
      <Columns>64</Columns>
      <FrameTime>
    <FrameReadTime>0.05016</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB8FP1A</SubarrayName>
      <Rows>8</Rows>
      <Columns>8</Columns>
      <FrameTime>
    <FrameReadTime>0.00220</FrameReadTime>
      </FrameTime>
      <USEAFTERDATE>2016-001/00:00:00</USEAFTERDATE>
    </Subarray>
    <Subarray>
      <SubarrayName>SUB8FP1B</SubarrayName>
      <Rows>8</Rows>
      <Columns>8</Columns>
      <FrameTime>
    <FrameReadTime>0.00220</FrameReadTime>
